name: quick_cab
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons:
  flutter_screenutil:
  country_pickers: ^2.0.0
  im_stepper: ^0.1.3
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.4
  google_maps_flutter: ^2.1.3
  animated_splash_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/




  fonts:
   - family: Avenir
     fonts:
       - asset: fonts/AvenirLTStd-Black.otf
       - asset: fonts/AvenirLTStd-Book.otf
       - asset: fonts/AvenirLTStd-Roman.otf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
